### ISSUE TITLE
Unable to open 2 240 000 x 15 pixels file

### ISSUE THREAD

**Issue by GoldenretriverYT** [delhoume/vliv#1]
Trying to open a 2,24million x 15 pixels files causes a runtime error.
![image](https://user-images.githubusercontent.com/49924528/141104266-e3cc0107-8b65-4bcc-857a-64f0b05c9445.png)

**Comment by delhoume** [comment]
What is the format of your image ?
Can it be opened by other viewers ?
Is there's a way to access this image to test ?

I am a bit surprised as I am not aware of image formats that support this kind of dimensions.

**Comment by GoldenretriverYT** [comment]
Well, I actually think it might be a general limit of PNG that I reached. Because Windows does not really show me the file size, and I just know it because its 100 24000x15 pngs stitched together. Every renderer I tried breaks apart. I am closing this issue since I think its most likely a limitation thats probably impossible to exceed.

**Comment by delhoume** [comment]
PNG format should allow for much larger dimensions, so it might be a Windows limitation for bitmaps.
In the PNG case Vliv will try to load the entire image whereas for TIFF (tiled) it will only load visible tiles.
If you are able to convert the image to a tiled format such as TIFF (with vips for example - https://www.libvips.org/),
you might be able to view it with Vliv.
If you can give me a way to download the image I will be able to have a look.

**Comment by delhoume** [comment]
![image](https://user-images.githubusercontent.com/1763447/141271528-67c6c755-95bf-4556-8b00-27791de96d33.png)

as you can see Vliv can open a 2 000 000 x 15  PPM image (P6) that is 90,000,018 bytes without any problem.
It creates "virtual tiles" that are 256x256 and loads them as they are displayed.

I suspect the issue is in libpng.

Maybe you can switch to PPM format, that would be 3 bytes per pixel uncompressed but the virtual tiling feature of Vliv allows almost infinite dimensions PPM images to be displayed.

A P6 PPM image is very simple : a simple ascii header
P6
width height
256

followed by 3 x width x height bytes.

That makes them very easy to generate.
