### ISSUE TITLE
Bad BMP rendering

### ISSUE THREAD

**Issue by deltabeard** [delhoume/vliv#3]
Hello,

Viewing a BMP file in vliv looks different than in other image viewers, such as *Photos* and *Irfanview*:
![image](https://user-images.githubusercontent.com/3747104/154739243-30525cb5-fcc3-4558-ab36-704a413918b7.png)

The image was generated by the SDL_SaveBMP function of SDL2. The image can be found in:
[00000000BAA76904.zip](https://github.com/delhoume/vliv/files/8099472/00000000BAA76904.zip)

Thanks and great work on the project.

**Comment by delhoume** [comment]
![image](https://user-images.githubusercontent.com/1763447/154836978-c4e42db7-7397-457e-b1b2-8f069239eb50.png)
it looks like Vliv is opening correctly your image, but it displays it at coordinates 0,0 instead of centering it in the window like other viewers. If you resize IrfanViews's window to a small size, you'll see that the display is the same.
And in  Vliv the minimal window  size is calculated so that the toolbar is always completely visible.
The displayed image dimensions are correct (163x51).

**Comment by deltabeard** [comment]
Your image also has the same issue whereby red and blue lines can be seen in the image shown in vliv, but not in other image viewers.

![Screenshot_20220220-174921_Firefox](https://user-images.githubusercontent.com/3747104/154857567-bc42a52a-4ea4-494d-b2bd-c9a8005b76e1.png)

**Comment by delhoume** [comment]
I did not get it, I will have a look

**Comment by delhoume** [comment]
![image](https://user-images.githubusercontent.com/1763447/154860626-76ee3649-67d9-46a1-ae47-21dcf772780e.png)
Should be fixed in 2.5.6 (a bad offset to image data was computed instead of using the header offset)

**Comment by deltabeard** [comment]
Confirmed fixed.
