### ISSUE TITLE
Top-Town Bitmaps not working

### ISSUE THREAD

**Issue by MartinKuschnik** [delhoume/vliv#6]
Hi,

the Bitmap format also supports top-down images. 
(see https://learn.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-bitmapv5header)

vliv only shows a black area for this kind of files.

Here you have two example images: [images.zip](https://github.com/delhoume/vliv/files/10294481/images.zip)

**Comment by delhoume** [comment]
I will have a look, the support for BM files is deliberately not very broad, I only load some BI_RGB and BI_BITFIELDS files, with various bit depth and with no compression.
I should however allow top-down BMPs to load, because they are always BI_RGB or BI_BITFIELDS, it should be a simple change in my code.
I will make sure your sample top-down image can be loaded.

**Comment by delhoume** [comment]
Support added, verified using the image provided

**Comment by MartinKuschnik** [comment]
Works  - Thanks!
